name: recognify
description: "Porto Web"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
